import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App with Moesif</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js API is running!</h1>

        <div className={styles.description}>
          Test <code>/api/hello</code> and other API endpoints
          via an API platform like Postman.
        </div>

        <div className={styles.description}>
          Please see the{" "}
          <a href="https://nextjs.org/docs/api-routes/introduction">
            documentation
          </a>{" "}
          for more information about API routes in Next.js
        </div>
      </main>
    </div>
  );
}
